/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import util.Clock;
import util.Tick;

/**
 *
 * @author JIBOYE, Oluwagbemiro Olaoluwa <gbenroscience@yahoo.com>
 */
public class ClockSettings extends javax.swing.JFrame {

    Clock clockFrame;
    /**
     * Used when the clockCircleWidthSpinner is jumping between the 2 circles.
     * When this attribute is true, the spinner retrieves the former value of
     * the width of the circle, and then sets this attribute to false.Then it
     * starts its value spinning action again.
     */
    private boolean toggleclockCircleWidthSpinnerValue;
    /**
     * Used when the clockHandLengthSpinner is jumping between the 3 hands. When
     * this attribute is true, the spinner retrieves the former value of the
     * length of the clock hand, and then sets this attribute to false.Then it
     * starts its value spinning action again.
     */
    private boolean toggleclockHandLengthSpinnerValue;
    /**
     * Retrieves a color from the JColorChooser attribute of this class.
     */
    private Color color;

    /**
     * Creates new form ClockSettings
     */
    public ClockSettings(Clock clock) {
        super("PROPERTIES");

        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ClockSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();

        this.clockFrame = clock;

        clockWidthSpinner.setModel(new SpinnerNumberModel(clock.getDiameter(), 0, Toolkit.getDefaultToolkit().getScreenSize().width, 1));
        clockCenterWidthSpinner.setModel(new SpinnerNumberModel(clock.getCenterSpotWidth(), 0, 200, 1));
        clockHandLengthSpinner.setModel(new SpinnerNumberModel(0.9, 0.0, 1.0, 0.01));

        clockCircleWidthSpinner.setModel(new SpinnerNumberModel(clock.getOuterCircleAsFractionOfFrameSize(), 0, 1.0, 0.01));

        clockCircleCombo.removeAllItems();
        clockCircleCombo.addItem("Outer Circle");
        clockCircleCombo.addItem("Inner Circle");

        clockHandCombo.removeAllItems();
        clockHandCombo.addItem("Seconds Hand");
        clockHandCombo.addItem("Minutes Hand");
        clockHandCombo.addItem("Hour Hand");

        clockComponentCombo.removeAllItems();
        clockComponentCombo.addItem("Seconds Hand");
        clockComponentCombo.addItem("Minutes Hand");
        clockComponentCombo.addItem("Hour Hand");
        clockComponentCombo.addItem("External Background");
        clockComponentCombo.addItem("Double Circle Background");
        clockComponentCombo.addItem("Inner Circle Background");
        clockComponentCombo.addItem("Center Circle");
        clockComponentCombo.addItem("All Clock Ticks");
        clockComponentCombo.addItem("Random Color For Ticks");

        clockCircleCombo.setActionCommand(String.valueOf(clockCircleCombo.getSelectedItem()));

        setPreferredSize(new Dimension(getPreferredSize().width, 1000));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        clockCircleCombo = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clockCircleWidthSpinner = new javax.swing.JSpinner();
        clockCenterWidthSpinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        clockWidthSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clockHandLengthSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        clockHandCombo = new javax.swing.JComboBox();
        clockComponentCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        colorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        panel.setBackground(new java.awt.Color(51, 51, 51));
        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel.setName("panel"); // NOI18N

        clockCircleCombo.setFont(new java.awt.Font("Tahoma 12", 1, 12)); // NOI18N
        clockCircleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clockCircleCombo.setName("clockCircleCombo"); // NOI18N
        clockCircleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockCircleComboActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial 12 12 12 12 12 12", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("SELECT CLOCK CIRCLE");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial 12 12 12 12 12 12 12", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("SET CIRCLE WIDTH AS FRACTION OF CLOCK WIDTH");
        jLabel15.setName("jLabel15"); // NOI18N

        clockCircleWidthSpinner.setName("clockCircleWidthSpinner"); // NOI18N
        clockCircleWidthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clockCircleWidthSpinnerStateChanged(evt);
            }
        });

        clockCenterWidthSpinner.setName("clockCenterWidthSpinner"); // NOI18N
        clockCenterWidthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clockCenterWidthSpinnerStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial 12 12 12 12 12 12 12", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("SET CLOCK CENTER WIDTH.");
        jLabel10.setName("jLabel10"); // NOI18N

        clockWidthSpinner.setName("clockWidthSpinner"); // NOI18N
        clockWidthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clockWidthSpinnerStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial 12 12 12 12", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("SET CLOCK WIDTH");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial 12 12 12 12 12 12", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("SET HAND LENGTH AS FRACTION OF INNER CLOCK CIRCLE WIDTH");
        jLabel9.setName("jLabel9"); // NOI18N

        clockHandLengthSpinner.setName("clockHandLengthSpinner"); // NOI18N
        clockHandLengthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clockHandLengthSpinnerStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial 12 12 12 12 12", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("SELECT CLOCK HAND");
        jLabel8.setName("jLabel8"); // NOI18N

        clockHandCombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clockHandCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clockHandCombo.setName("clockHandCombo"); // NOI18N
        clockHandCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockHandComboActionPerformed(evt);
            }
        });

        clockComponentCombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clockComponentCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clockComponentCombo.setName("clockComponentCombo"); // NOI18N
        clockComponentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockComponentComboActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial 12 12 12", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("SELECT CLOCK COMPONENT AND CHANGE ITS COLOR");
        jLabel6.setName("jLabel6"); // NOI18N

        colorButton.setBackground(new java.awt.Color(51, 51, 51));
        colorButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        colorButton.setForeground(new java.awt.Color(255, 255, 255));
        colorButton.setText("COLOR");
        colorButton.setName("colorButton"); // NOI18N
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(clockCircleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(clockCircleWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(clockWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(clockCenterWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(clockHandCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(clockComponentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(colorButton))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(clockHandLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockComponentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockCircleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockCircleWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(clockWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockCenterWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockHandCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockHandLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isToggleclockCircleWidthSpinnerValue() {
        return toggleclockCircleWidthSpinnerValue;
    }

    public void setToggleclockCircleWidthSpinnerValue(boolean toggleclockCircleWidthSpinnerValue) {
        this.toggleclockCircleWidthSpinnerValue = toggleclockCircleWidthSpinnerValue;
    }

    public void setToggleclockHandLengthSpinnerValue(boolean toggleclockHandLengthSpinnerValue) {
        this.toggleclockHandLengthSpinnerValue = toggleclockHandLengthSpinnerValue;
    }

    public boolean isToggleclockHandLengthSpinnerValue() {
        return toggleclockHandLengthSpinnerValue;
    }

    private void clockCircleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockCircleComboActionPerformed
        clockCircleCombo.setActionCommand(String.valueOf(clockCircleCombo.getSelectedItem()));
        setToggleclockCircleWidthSpinnerValue(true);
    }//GEN-LAST:event_clockCircleComboActionPerformed

    private void clockCircleWidthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clockCircleWidthSpinnerStateChanged

        if (clockCircleCombo.getActionCommand().equalsIgnoreCase("Outer Circle")) {
            if (isToggleclockCircleWidthSpinnerValue()) {
                clockCircleWidthSpinner.setValue(clockFrame.getOuterCircleAsFractionOfFrameSize());
                setToggleclockCircleWidthSpinnerValue(false);
            }
            clockFrame.setOuterCircleAsFractionOfFrameSize(Double.valueOf(String.valueOf(clockCircleWidthSpinner.getValue())));
        } else if (clockCircleCombo.getActionCommand().equalsIgnoreCase("Inner Circle")) {
            if (isToggleclockCircleWidthSpinnerValue()) {
                clockCircleWidthSpinner.setValue(clockFrame.getInnerCircleAsFractionOfFrameSize());
                setToggleclockCircleWidthSpinnerValue(false);
            }
            clockFrame.setInnerCircleAsFractionOfFrameSize(Double.valueOf(String.valueOf(clockCircleWidthSpinner.getValue())));
        }

    }//GEN-LAST:event_clockCircleWidthSpinnerStateChanged

    private void clockCenterWidthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clockCenterWidthSpinnerStateChanged
        clockFrame.setCenterSpotWidth(Integer.valueOf(String.valueOf(clockCenterWidthSpinner.getValue())));
    }//GEN-LAST:event_clockCenterWidthSpinnerStateChanged

    private void clockWidthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clockWidthSpinnerStateChanged
        clockFrame.setDiameter(Integer.valueOf(String.valueOf(clockWidthSpinner.getValue())));
    }//GEN-LAST:event_clockWidthSpinnerStateChanged

    private void clockHandLengthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clockHandLengthSpinnerStateChanged
        if (clockHandCombo.getActionCommand().equalsIgnoreCase("Seconds Hand")) {
            if (isToggleclockHandLengthSpinnerValue()) {
                clockHandLengthSpinner.setValue(clockFrame.secondsHand.getHandLengthAsFractionOfClockWidth());
                setToggleclockHandLengthSpinnerValue(false);
            }
            clockFrame.secondsHand.setHandLengthAsFractionOfClockWidth(Double.valueOf(String.valueOf(clockHandLengthSpinner.getValue())));
        } else if (clockHandCombo.getActionCommand().equalsIgnoreCase("Minutes Hand")) {
            if (isToggleclockHandLengthSpinnerValue()) {
                clockHandLengthSpinner.setValue(clockFrame.minuteHand.getHandLengthAsFractionOfClockWidth());
                setToggleclockHandLengthSpinnerValue(false);
            }
            clockFrame.minuteHand.setHandLengthAsFractionOfClockWidth(Double.valueOf(String.valueOf(clockHandLengthSpinner.getValue())));
        } else if (clockHandCombo.getActionCommand().equalsIgnoreCase("Hour Hand")) {
            if (isToggleclockHandLengthSpinnerValue()) {
                clockHandLengthSpinner.setValue(clockFrame.hourHand.getHandLengthAsFractionOfClockWidth());
                setToggleclockHandLengthSpinnerValue(false);
            }
            clockFrame.hourHand.setHandLengthAsFractionOfClockWidth(Double.valueOf(String.valueOf(clockHandLengthSpinner.getValue())));
        }
    }//GEN-LAST:event_clockHandLengthSpinnerStateChanged

    private void clockHandComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockHandComboActionPerformed
        clockHandCombo.setActionCommand(String.valueOf(clockHandCombo.getSelectedItem()));
        setToggleclockHandLengthSpinnerValue(true);
    }//GEN-LAST:event_clockHandComboActionPerformed

    private void clockComponentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockComponentComboActionPerformed
        clockComponentCombo.setActionCommand(String.valueOf(clockComponentCombo.getSelectedItem()));
        if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Random Color For Ticks")) {
            Tick[] ticks = clockFrame.getTicks();
            for (int i = 0; i < ticks.length; i++) {
                ticks[i].setColor(new Color(new Random().nextInt(256),
                        new Random().nextInt(256),
                        new Random().nextInt(256)));
            }
        }
    }//GEN-LAST:event_clockComponentComboActionPerformed

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        if (color == null) {
            color = Color.white;
        }
        
    
            JColorChooser chooser = new JColorChooser(color);
            chooser.setVisible(true);
            
                JDialog dialog = new JDialog(this, "SET CLOCK COMPONENT COLOR");
                dialog.add(chooser);
                dialog.setVisible(true);
                dialog.pack();
        
            chooser.getSelectionModel().addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
          color = chooser.getColor();           
        if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Seconds Hand")) {
            clockFrame.secondsHand.setColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Minutes Hand")) {
            clockFrame.minuteHand.setColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Hour Hand")) {
            clockFrame.hourHand.setColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("External Background")) {
            clockFrame.setOuterColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Double Circle Background")) {
            clockFrame.setMiddleColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Inner Circle Background")) {
            clockFrame.setInnerColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("Center Circle")) {
            clockFrame.setCenterSpotColor(color);
        } else if (clockComponentCombo.getActionCommand().equalsIgnoreCase("All Clock Ticks")) {
            Tick[] ticks = clockFrame.getTicks();
            for (int i = 0; i < ticks.length; i++) {
                ticks[i].setColor(color);
            }
        }
                
                
            }
        });
     //   color = JColorChooser.showDialog(panel, "SET CLOCK COMPONENT COLOR", color);

    
    }//GEN-LAST:event_colorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner clockCenterWidthSpinner;
    private javax.swing.JComboBox clockCircleCombo;
    private javax.swing.JSpinner clockCircleWidthSpinner;
    private javax.swing.JComboBox clockComponentCombo;
    private javax.swing.JComboBox clockHandCombo;
    private javax.swing.JSpinner clockHandLengthSpinner;
    private javax.swing.JSpinner clockWidthSpinner;
    private javax.swing.JButton colorButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
